language: ruby
sudo: false
cache: bundler
script: 'bundle exec rake test:coverage --trace'
before_install:
  - rvm get head # required by JRuby > 9.0.1.0
  - rvm reload
rvm:
  - 2.2
  - 2.3
  - ruby-head
  - jruby-head
  - jruby-9000
  - jruby-9.0.1.0

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-9000
